### PR TITLE
HTMLInjector matches ws/wss scheme to http/https scheme. Fixes #175.

### LINKED ISSUE #175: In a codespace, injected code trying to use ws instead of wss
When trying to use livepreview in a codespace on github.com with port forwards and an external browser, the below errors show up in the console.

Note that this is distinct from attempting to use the livepreview as a tab inside of the codespace, but using the automatic port forwards and an external browser instance.

"___vscode_livepreview_injected_script:28 Mixed Content: The page at 'https://XXX-3004.githubpreview.dev/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://XXX-3005.githubpreview.dev/'. This request has been blocked; this endpoint must be available over WSS."

and

"Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at onLoad (https://XXX-3004.githubpreview.dev/___vscode_livepreview_injected_script:28:19)
    at HTMLDocument.<anonymous> (https://XXX-3004.githubpreview.dev/___vscode_livepreview_injected_script:11:2)"

### PR DESCRIPTION
**Pull request by jeremysf**
Fixes https://github.com/microsoft/vscode-livepreview/issues/175.

When attempting to use livepreview from a codespace, codespace serves up the content over HTTPS via port forwards.

The injected scripts attempt to open the web socket using the `ws` protocol instead of the `wss` protocol, resulting in Chrome blocking opening the WebSocket.

This pull request updates the injected code to conditionally use the `ws` or `wss` protocol to match the HTTP scheme.

### CODE REVIEW

**Comment by jeremysf** [comment]
Hmm, while this no longer throws the security error, I think I must be missing something as the websocket seems to be stuck in state "pending".

**Comment by jeremysf** [comment]
Tested using the attached VSIX (drag/dropped into codespace and installed via right clicking it). Can confirm websocket connects correctly via `wss` and changes to HTML files in the codespace result in receiving a websocket message and subsequently refreshing the HTML page

[live-server-0.2.9.vsix.zip](https://github.com/microsoft/vscode-livepreview/files/7552266/live-server-0.2.9.vsix.zip)
).

**Comment by andreamah** [comment]
Hi! Apologies for getting back to you so late, but does this still work with codespaces better than what is in the latest live preview? Chrome in the external browser preview seemed to display the content just fine for me using the marketplace version.

**Comment by mpcref** [comment]
Any particular reason why this very simple yet important change hasn't been merged after 8 months?

**Comment by andreamah** [comment]
updated to use wsPath, which was added after this PR was created. thanks for the PR!

**Review by andreamah — APPROVED** [review]

**Review by tanhakabir — APPROVED** [review]

**Pull request merged**
